server:
  port: 8889
spring:
  application:
    name: configserver
  profiles:
    active: native, guangdong-dev
  cloud:
    config:
      server:
        native:
          search-locations:
#            - classpath:/
            - classpath:/guangdong/
            - classpath:/default/
            - classpath:/config/
            - classpath:/config/configclient/
            - classpath:/config/guangdong/
            - classpath:/config/default/
            - file:./
#            - file:./config/*/
            - file:./config/